# Generated by Django 4.2.1 on 2023-05-16 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_composition_alter_product_price_and_more'),
        ('orders', '0002_alter_order_options_alter_productorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='orders.ProductOrder', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.staff'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productorder',
            table=None,
        ),
        migrations.AlterModelTable(
            name='staff',
            table=None,
        ),
    ]
