# Generated by Django 4.2.1 on 2023-05-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('DI', 'Директор'), ('AD', 'Администратор'), ('MG', 'Менеджер'), ('CA', 'Кассир')], default='MG', max_length=255)),
                ('labor_contract', models.IntegerField()),
            ],
        ),
    ]
