# Generated by Django 4.2.1 on 2023-05-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(choices=[('main', 'Основное меню'), ('top', 'Верхнее меню')], default='main', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
